extend type Query {
  user(id: ID!): User
  allUsers: [User]!
}

extend type Mutation {
  updateUser(input: updateUserInput!): updatedUser!
}

type User {
  id: ID!
  email: String
  avatarURL: String
  firstName: String
  lastName: String
  trips: [Trip]
}

input updateUserInput {
  id: ID!
  name: String
}

type updatedUser {
  id: ID!
  name: String
}
