extend type Query {
  user(email: String!): User
  allUsers: [User]!
  self: User!
}

extend type Mutation {
  register(email: String!, password: String!, user: UserInput): User!
  login(email: String!, password: String!): String
  updateUser(id: ID!, update: updateUserInput): User!
}

type User {
  email: String!
  avatarURL: String
  firstName: String
  lastName: String
  trips: [Trip]
}

input UserInput {
  avatarURL: String
  firstName: String
  lastName: String
}

input updateUserInput {
  firstName: String
  lastName: String
  email: String
  avatarURL: String
}

input createUserInput {
  email: String!
  avatarURL: String
  firstName: String
  lastName: String
}
