extend type Query {
  trip(id: ID!): Trip
  allTrips: [Trip]!
}

extend type Mutation {
  createTrip(trip: createTripInput!, userID: ID): Trip!
  updateTrip(id: ID!, trip: updateTripInput): Trip!
  addParticipant(user: ID!): Trip!
  # updateTrip(input: updateTripInput!): updatedTrip!
  # createTrip(input: createTripInput!, userID: String): Trip
}

type Trip {
  id: ID!
  name: String!
  participants: [User]!
  destination: DestinationObject
  budget: BudgetObject!
  timeFrame: TimeFrameObject
}

type DestinationObject {
  chosenDestination: Destination
  suggestions: [Destination]!
  isDictated: Boolean
}

type Destination {
  key: ID!
  name: String!
  voters: [User]
  creator: User
}

type BudgetObject {
  chosenBudget: Budget
  suggestions: [Budget]!
  isDictated: Boolean
}

type TimeFrameObject {
  chosenTimeFrame: TimeFrame
  suggestions: [TimeFrame]!
  isDictated: Boolean
}

type TimeFrame {
  startDate: String
  endDate: String
  voters: [User]
  creator: User
}

type Budget {
  id: ID!
  value: Int!
  voters: [User]
  creator: User
}

input updateTripInput {
  id: ID!
  name: String
  participants: [String]
  destination: DestinationObjectInput
  budget: BudgetObjectInput
  timeFrame: TimeFrameObjectInput
}

input DestinationObjectInput {
  suggestions: [String]
  isDictated: Boolean
}

input BudgetObjectInput {
  suggestions: [Int]
  isDictated: Boolean
}

input createTripInput {
  name: String!
  participants: [String]
  destination: DestinationObjectInput
  budget: BudgetObjectInput
  timeFrame: TimeFrameObjectInput
}

input TimeFrameInput {
  startDate: String
  endDate: String
}

input TimeFrameObjectInput {
  suggestions: [TimeFrameInput]
  isDictated: Boolean
}
